name: Debug release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }} 
      - name: Print the input tag to STDOUT
        run: echo  The tags are $GITHUB_REF
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - uses: jungwinter/split@v2
        id: split
        with:
          separator: "-"
          msg: '${{ steps.get_version.outputs.VERSION }}' # ${{ steps.split.outputs._0 }}
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ steps.split.outputs._0 }}