name: Create Release

on:
  workflow_dispatch:
    branches: main
    inputs:
      tag:
        description: "Tag to build release with"
        required: true
        type: string
        
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  print-tag:
    runs-on: ubuntu-latest 
    steps:
      - 
        name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tag }} 
      - 
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }} 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      