name: Debug release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest 
    steps:
      - 
        name: Print the input tag to STDOUT
        run: echo  The tags are ${{ GITHUB_REF }} 
      - 
        uses: actions/checkout@v3
        with:
          ref: ${{ GITHUB_REF }} 